### ISSUE TITLE
请教一下这个mark1和mark2到底有啥用

### ISSUE THREAD

**Issue by AChildofGod** [ZQPei/Sorting_Visualization#3]
你难道没发现这个mark2永远都是None吗，我不知道这个参数是怎么传递过去的，也不知道那个mark2的BLUE有啥用，永远都不可能执行这一行代码，自己试了一下交换的时候的标记也只见到红色的标记，并没有见到蓝色的标记
![QQ图片20190823013007](https://user-images.githubusercontent.com/50610708/63536167-9ed9cd00-c545-11e9-83a2-27cea9887de7.png)

**Comment by ZQPei** [comment]
这个mark2一开始想用，但是后来没用到，同时我也不想删掉，可能以后会用到，就是这样了，哈哈
